Repository boostcamp-2020/Project18-A-BoostPocket, pull requests merged in 2020-12, with the labels that each got.

#97 여행 생성 시 환욜 요청 기능 구현
  BoostPocket/BoostPocket/Extensions/Date+ConvertToString.swift
  BoostPocket/BoostPocket/Models/DataModelInfo.swift
  BoostPocket/BoostPocket/Models/PersistenceManager.swift
  BoostPocket/BoostPocket/SceneDelegate.swift
  BoostPocket/BoostPocket/TravelListScene/TravelListViewModel.swift
  BoostPocket/BoostPocket/TravelListScene/View/TravelListViewController.swift
  BoostPocket/BoostPocketTests/CountryTests/CountryProviderTests.swift
  BoostPocket/BoostPocketTests/CountryTests/CountryViewModelTests.swift
  BoostPocket/BoostPocketTests/PersistenceManagerTests/PersistenceManagerStub.swift
  BoostPocket/BoostPocketTests/PersistenceManagerTests/PersistenceManagerTests.swift
  BoostPocket/BoostPocketTests/TravelTests/TravelProviderTests.swift
  BoostPocket/BoostPocketTests/TravelTests/TravelViewModelTests.swift
Labels: Feature 🎨

#99 여행 프로필 datePicker 구현
  BoostPocket/BoostPocket/TravelDetailScene/MemoEditViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
  BoostPocket/BoostPocket/TravelDetailScene/TravelProfileViewController.swift
  BoostPocket/BoostPocket/TravelListScene/View/TravelListViewController.swift
Labels: Feature 🎨

#98 여행 프로필에서 커버이미지 변경 기능
  BoostPocket/BoostPocket/Info.plist
  BoostPocket/BoostPocket/Models/DataModelInfo.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
  BoostPocket/BoostPocket/TravelDetailScene/TravelProfileViewController.swift
  BoostPocket/BoostPocket/TravelListScene/TravelListViewModel.swift
  BoostPocket/BoostPocket/TravelListScene/View/TravelListViewController.swift
  BoostPocket/BoostPocketTests/TravelTests/TravelViewModelTests.swift
Labels: Feature 🎨

#101 PersistenceManager, Provider 리팩토링
  BoostPocket/.swiftlint.yml
  BoostPocket/BoostPocket/CountryListScene/CountryListViewModel.swift
  BoostPocket/BoostPocket/CountryListScene/CountryProvider.swift
  BoostPocket/BoostPocket/CountryListScene/View/CountryListViewController.swift
  BoostPocket/BoostPocket/Models/PersistenceManager.swift
  BoostPocket/BoostPocket/SceneDelegate.swift
  BoostPocket/BoostPocket/TravelDetailScene/TitleEditViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetailTabbarController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelProfileViewController.swift
  BoostPocket/BoostPocket/TravelListScene/TravelListViewModel.swift
  BoostPocket/BoostPocket/TravelListScene/TravelProvider.swift
  BoostPocket/BoostPocket/TravelListScene/View/TravelListViewController.swift
  BoostPocket/BoostPocketTests/CountryTests/CountryProviderTests.swift
  BoostPocket/BoostPocketTests/CountryTests/CountryViewModelTests.swift
  BoostPocket/BoostPocketTests/PersistenceManagerTests/PersistenceManagerTests.swift
  BoostPocket/BoostPocketTests/TravelTests/TravelProviderTests.swift
  BoostPocket/BoostPocketTests/TravelTests/TravelViewModelTests.swift
  BoostPocket/NetworkManager/DataLoader.swift
Labels: Bug 🐞, Refactoring ✒

#102 여행 프로필 화면 Constraints 수정
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
Labels: Bug 🐞

#106 레이아웃 오류 수정
  BoostPocket/BoostPocket/Base.lproj/Main.storyboard
  BoostPocket/BoostPocket/CountryListScene/View/CountryListViewController.swift
  BoostPocket/BoostPocket/CustomView/PaddedLabel.swift
  BoostPocket/BoostPocket/Extensions/Date+ConvertToString.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
  BoostPocket/BoostPocket/TravelDetailScene/TravelProfileViewController.swift
  BoostPocket/BoostPocket/TravelListScene/TravelItemViewModel.swift
  BoostPocket/BoostPocket/TravelListScene/View/TravelCell.xib
  BoostPocket/BoostPocket/TravelListScene/View/TravelHeaderCell.swift
  BoostPocket/BoostPocket/TravelListScene/View/TravelListViewController.swift
Labels: Bug 🐞

#107 여행 삭제 경고 alert 기능 구현
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
  BoostPocket/BoostPocket/TravelDetailScene/TravelProfileViewController.swift
Labels: Feature 🎨

#110 setupCountries, filterCountries 함수 이동/수정/테스트코드 작성
  BoostPocket/BoostPocket/Models/PersistenceManager.swift
  BoostPocket/BoostPocket/SceneDelegate.swift
  BoostPocket/BoostPocketTests/PersistenceManagerTests/PersistenceManagerTests.swift
Labels: Refactoring ✒, Test :test_tube:

#113 다양한 크기의 appIcon 추가
  BoostPocket/BoostPocket/Assets.xcassets/AppIcon.appiconset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/AppIcon.appiconset/appIcon.png
  BoostPocket/BoostPocket/Assets.xcassets/AppIcon.appiconset/appIcon1024.png
  BoostPocket/BoostPocket/Assets.xcassets/AppIcon.appiconset/appIcon120.png
  BoostPocket/BoostPocket/Assets.xcassets/AppIcon.appiconset/appIcon152.png
  BoostPocket/BoostPocket/Assets.xcassets/AppIcon.appiconset/appIcon167.png
  BoostPocket/BoostPocket/Assets.xcassets/AppIcon.appiconset/appIcon76.png
  BoostPocket/BoostPocket/Assets.xcassets/AppIcon.appiconset/image.png
Labels: Feature 🎨

#114 여행 삭제 alert 텍스트 색 변경
  BoostPocket/BoostPocket/TravelDetailScene/TravelProfileViewController.swift
Labels: Feature 🎨

#116 Travel 관련 테스트코드 개선
  BoostPocket/BoostPocket/Models/PersistenceManager.swift
  BoostPocket/BoostPocket/SceneDelegate.swift
  BoostPocket/BoostPocketTests/TravelTests/TravelProviderTests.swift
  BoostPocket/BoostPocketTests/TravelTests/TravelViewModelTests.swift
Labels: Refactoring ✒, Test :test_tube:

#118 History DataModel 추가
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/BoostPocket.xcdatamodeld/BoostPocket.xcdatamodel/contents
  BoostPocket/BoostPocket/CoreDataModels/History+CoreDataClass.swift
  BoostPocket/BoostPocket/CoreDataModels/History+CoreDataProperties.swift
  BoostPocket/BoostPocket/Models/DataModelInfo.swift
  BoostPocket/BoostPocket/Models/PersistenceManager.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryItemViewModel.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListViewModel.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryProvider.swift
  BoostPocket/BoostPocket/TravelListScene/TravelItemViewModel.swift
  BoostPocket/BoostPocketTests/HistoryTests/HistoryProviderTests.swift
  BoostPocket/BoostPocketTests/HistoryTests/HistoryViewModelTests.swift
  BoostPocket/BoostPocketTests/PersistenceManagerTests/PersistenceManagerTests.swift
  BoostPocket/BoostPocketTests/TravelTests/TravelViewModelTests.swift
Labels: Feature 🎨

#119 지출, 수입관련(History) 엔티티 설계, CRUD 기능 구현
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/CountryListScene/View/CountryListViewController.swift
  BoostPocket/BoostPocket/Models/PersistenceManager.swift
  BoostPocket/BoostPocket/SceneDelegate.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryItemViewModel.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListViewModel.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryProvider.swift
  BoostPocket/BoostPocket/TravelListScene/TravelItemViewModel.swift
  BoostPocket/BoostPocket/TravelListScene/TravelListViewModel.swift
  BoostPocket/BoostPocket/TravelListScene/View/TravelListViewController.swift
  BoostPocket/BoostPocketTests/HistoryTests/HistoryProviderTests.swift
  BoostPocket/BoostPocketTests/HistoryTests/HistoryViewModelTests.swift
  BoostPocket/BoostPocketTests/TravelTests/TravelViewModelTests.swift
Labels: Feature 🎨, Test :test_tube:

#120 지출 목록 테이블뷰 구현
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/Assets.xcassets/lightMainColor.colorset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/관광.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/관광.imageset/관광.png
  BoostPocket/BoostPocket/Assets.xcassets/교통.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/교통.imageset/교통.png
  BoostPocket/BoostPocket/Assets.xcassets/기타.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/기타.imageset/Etc.png
  BoostPocket/BoostPocket/Assets.xcassets/쇼핑.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/쇼핑.imageset/쇼핑.png
  BoostPocket/BoostPocket/Assets.xcassets/숙박.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/숙박.imageset/숙박.png
  BoostPocket/BoostPocket/Assets.xcassets/식비.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/식비.imageset/식비.png
  BoostPocket/BoostPocket/Assets.xcassets/예산 금액 추가.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/예산 금액 추가.imageset/예산 금액 추가.png
  BoostPocket/BoostPocket/Extensions/Date+ConvertToString.swift
  BoostPocket/BoostPocket/Extensions/Double+Comma.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryCell.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryCell.xib
  BoostPocket/BoostPocket/TravelDetailScene/HistoryHeaderCell.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryHeaderCell.xib
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
Labels: Feature 🎨

#124 지출 화면 TravelItemViewModel 적용
  BoostPocket/BoostPocket/TravelDetailScene/HistoryCell.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetailTabbarController.swift
  BoostPocket/BoostPocket/TravelListScene/TravelItemViewModel.swift
Labels: Feature 🎨

#126 History 필터기능 구현 및 지출/수입 추가화면 간단한 UI 틀
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryViewController.xib
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelListScene/TravelItemViewModel.swift
  BoostPocket/BoostPocketTests/PersistenceManagerTests/PersistenceManagerTests.swift
Labels: Bug 🐞, Feature 🎨

#127 지출 목록 화면 날짜 StackView 구현
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/Base.lproj/Main.storyboard
  BoostPocket/BoostPocket/Extensions/Date+ConvertToString.swift
  BoostPocket/BoostPocket/Extensions/Date+PeriodOfDates.swift
  BoostPocket/BoostPocket/TravelDetailScene/DayCell.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryCell.xib
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
Labels: Feature 🎨

#131 지출 상세화면 구현
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/TravelDetailScene/HistoryDetailViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
Labels: Feature 🎨

#132 지출 목록 화면 요소 구현
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/Assets.xcassets/lightMainColor.colorset/Contents.json
  BoostPocket/BoostPocket/Extensions/Date+PeriodOfDates.swift
  BoostPocket/BoostPocket/TravelDetailScene/DayCell.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryHeaderCell.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListSectionHeader.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
  BoostPocket/BoostPocket/TravelDetailScene/TravelProfileViewController.swift
  BoostPocket/BoostPocket/TravelListScene/TravelItemViewModel.swift
Labels: Feature 🎨, Refactoring ✒

#133 지출추가화면 구현
  BoostPocket/BoostPocket/Assets.xcassets/관광.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/관광.imageset/관광-1.png
  BoostPocket/BoostPocket/Extensions/Double+Comma.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryViewController.xib
  BoostPocket/BoostPocket/TravelDetailScene/HistoryHeaderCell.xib
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/MemoEditViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TitleEditViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetailTabbarController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelProfileViewController.swift
  BoostPocket/BoostPocket/TravelListScene/View/TravelListViewController.swift
Labels: Feature 🎨

#135 Asset 사진 버그 수정
  BoostPocket/BoostPocket/Assets.xcassets/관광.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/관광.imageset/관광.png
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListViewController.swift
Labels: Bug 🐞

#137 지출 목록 화면 버그 수정
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/Assets.xcassets/Etc.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/Etc.imageset/Etc.png
  BoostPocket/BoostPocket/Assets.xcassets/accommodation.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/accommodation.imageset/숙박.png
  BoostPocket/BoostPocket/Assets.xcassets/food.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/food.imageset/식비.png
  BoostPocket/BoostPocket/Assets.xcassets/income.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/income.imageset/예산 금액 추가.png
  BoostPocket/BoostPocket/Assets.xcassets/shopping.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/shopping.imageset/쇼핑.png
  BoostPocket/BoostPocket/Assets.xcassets/tourism.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/tourism.imageset/관광.png
  BoostPocket/BoostPocket/Assets.xcassets/transportation.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/transportation.imageset/교통.png
  BoostPocket/BoostPocket/Extensions/Date+ConvertToString.swift
  BoostPocket/BoostPocket/Extensions/Date+PeriodOfDates.swift
  BoostPocket/BoostPocket/Extensions/UIStackView+RemoveAll.swift
  BoostPocket/BoostPocket/Models/DataModelInfo.swift
  BoostPocket/BoostPocket/Models/PersistenceManager.swift
  BoostPocket/BoostPocket/TravelDetailScene/DayCell.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryCell.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryDetailViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
  BoostPocket/BoostPocketTests/CountryTests/CountryProviderTests.swift
  BoostPocket/BoostPocketTests/CountryTests/CountryViewModelTests.swift
  BoostPocket/BoostPocketTests/HistoryTests/HistoryProviderTests.swift
  BoostPocket/BoostPocketTests/HistoryTests/HistoryViewModelTests.swift
  BoostPocket/BoostPocketTests/PersistenceManagerTests/PersistenceManagerTests.swift
  BoostPocket/BoostPocketTests/TravelTests/TravelViewModelTests.swift
Labels: HotFix 🚨

#138 소수점 여러개일 때 크래시나는 현상 에러핸들링
  BoostPocket/BoostPocket/Assets.xcassets/accommodation.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/accommodation.imageset/accommodation.png
  BoostPocket/BoostPocket/Assets.xcassets/food.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/food.imageset/food.png
  BoostPocket/BoostPocket/Assets.xcassets/income.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/income.imageset/income.png
  BoostPocket/BoostPocket/Assets.xcassets/shopping.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/shopping.imageset/shopping.png
  BoostPocket/BoostPocket/Assets.xcassets/tourism.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/tourism.imageset/tourism.png
  BoostPocket/BoostPocket/Assets.xcassets/transportation.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/transportation.imageset/transportation.png
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListViewController.swift
Labels: HotFix 🚨

#139 etc 파일명 수정
  BoostPocket/BoostPocket/Assets.xcassets/Etc.imageset/Contents.json
Labels: HotFix 🚨

#146 기록추가화면 - 지출/수입에 대해 대응할 수 있도록 개선
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/Base.lproj/Main.storyboard
  BoostPocket/BoostPocket/Extensions/Character+isOperation.swift
  BoostPocket/BoostPocket/Extensions/Date+PeriodOfDates.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryViewController.xib
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
  BoostPocket/Podfile
  BoostPocket/Podfile.lock
Labels: Feature 🎨

#154 메모수정 기능 구현
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/MemoEditViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelProfileViewController.swift
Labels: Feature 🎨

#159 Toaster Cocoapod 추가
  BoostPocket/BoostPocket/Models/PersistenceManager.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelListScene/TravelItemViewModel.swift
  BoostPocket/Podfile
  BoostPocket/Podfile.lock
Labels: Feature 🎨

#162 상세 화면 데이터 적용(진행중)
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/Assets.xcassets/categories/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/categories/etc.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/categories/etc.imageset/etc.png
  BoostPocket/BoostPocket/Assets.xcassets/categories/food.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/categories/food.imageset/food.png
  BoostPocket/BoostPocket/Assets.xcassets/categories/income.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/categories/income.imageset/income.png
  BoostPocket/BoostPocket/Assets.xcassets/categories/shopping.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/categories/shopping.imageset/shopping.png
  BoostPocket/BoostPocket/Assets.xcassets/categories/tourism.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/categories/tourism.imageset/tourism.png
  BoostPocket/BoostPocket/Assets.xcassets/categories/transportation.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/categories/transportation.imageset/transportation.png
  BoostPocket/BoostPocket/Assets.xcassets/historyImage.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/historyImage.imageset/historyImage.png
  BoostPocket/BoostPocket/Assets.xcassets/incomeColor.colorset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/isPrepareFalse.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/isPrepareFalse.imageset/isPrepareFalse.png
  BoostPocket/BoostPocket/Assets.xcassets/isPrepareTrue.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/isPrepareTrue.imageset/isPrepareTrue.png
  BoostPocket/BoostPocket/Assets.xcassets/layouts/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/layouts/default.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/layouts/default.imageset/default.png
  BoostPocket/BoostPocket/Assets.xcassets/layouts/hamburger.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/layouts/hamburger.imageset/hamburger.png
  BoostPocket/BoostPocket/Assets.xcassets/layouts/rectangle.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/layouts/rectangle.imageset/rectangle.png
  BoostPocket/BoostPocket/Assets.xcassets/layouts/square.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/layouts/square.imageset/square.png
  BoostPocket/BoostPocket/Extensions/Date+ConvertToString.swift
  BoostPocket/BoostPocket/Extensions/Double+NumberFormat.swift
  BoostPocket/BoostPocket/Extensions/String+CurrencySymbol.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryDetailViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
Labels: Feature 🎨

#160 HistoryFilter 모델 생성
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/TravelDetailScene/HistoryFilter.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
  BoostPocket/BoostPocketTests/HistoryTests/HistoryFilterTests.swift
  BoostPocket/BoostPocketTests/HistoryTests/HistoryItemViewModelStub.swift
Labels: Refactoring ✒

#163 HistoryListViewController 에러 수정
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListViewController.swift
Labels: Bug 🐞

#165 Country Entity에 identifier attribute 추가
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/BoostPocket.xcdatamodeld/BoostPocket.xcdatamodel/contents
  BoostPocket/BoostPocket/CoreDataModels/Country+CoreDataClass.swift
  BoostPocket/BoostPocket/CoreDataModels/Country+CoreDataProperties.swift
  BoostPocket/BoostPocket/CountryListScene/CountryListViewModel.swift
  BoostPocket/BoostPocket/CountryListScene/CountryProvider.swift
  BoostPocket/BoostPocket/Models/DataModelInfo.swift
  BoostPocket/BoostPocket/Models/PersistenceManager.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryDetailViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelListScene/TravelItemViewModel.swift
  BoostPocket/BoostPocketTests/CountryTests/CountryProviderTests.swift
  BoostPocket/BoostPocketTests/CountryTests/CountryStub.swift
  BoostPocket/BoostPocketTests/CountryTests/CountryViewModelTests.swift
  BoostPocket/BoostPocketTests/PersistenceManagerTests/PersistenceManagerTests.swift
Labels: Feature 🎨

#164 Date 관련 리팩토링
  BoostPocket/BoostPocket/Extensions/Date+ConvertToString.swift
  BoostPocket/BoostPocket/Extensions/Date+PeriodOfDates.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListViewController.swift
Labels: Refactoring ✒

#168 필요 없는 테스트코드 삭제
  BoostPocket/BoostPocket/CountryListScene/CountryProvider.swift
  BoostPocket/BoostPocketTests/CountryTests/CountryProviderTests.swift
  BoostPocket/BoostPocketTests/CountryTests/CountryStub.swift
  BoostPocket/BoostPocketTests/CountryTests/CountryViewModelTests.swift
Labels: Refactoring ✒

#170 지출/예산 화면 카테고리 collectionView 추가
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/Assets.xcassets/categories/accommodation.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/categories/accommodation.imageset/accommodation.png
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryViewController.xib
  BoostPocket/BoostPocket/TravelDetailScene/CategoryCollectionViewCell.swift
  BoostPocket/BoostPocket/TravelDetailScene/CategoryCollectionViewCell.xib
  BoostPocket/BoostPocket/TravelDetailScene/HistoryCell.xib
  BoostPocket/BoostPocket/TravelDetailScene/HistoryHeaderCell.xib
Labels: Feature 🎨

#171 History Detail 화면 데이터 적용
  BoostPocket/BoostPocket/Extensions/Double+NumberFormat.swift
  BoostPocket/BoostPocket/Extensions/String+CurrencySymbol.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryDetailViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListViewController.swift
Labels: Feature 🎨

#173 History 관련 Delegate Pattern 적용
  BoostPocket/BoostPocket/Extensions/Double+NumberFormat.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryDetailViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
Labels: Feature 🎨

#176 지출/예산 상세 -> 편집 버튼으로 이동하여 수정된 데이터 반영 기능 구현
  BoostPocket/BoostPocket/CoreDataModels/Country+CoreDataProperties.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryDetailViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
Labels: Feature 🎨

#175 지출 목록 화면 금액 뷰, selected 효과 적용
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/TravelDetailScene/DayCell.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryHeaderCell.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryHeaderCell.xib
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TotalAmountView.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
Labels: Feature 🎨

#181 지출 관련 디테일 추가
  BoostPocket/BoostPocket/Base.lproj/Main.storyboard
  BoostPocket/BoostPocket/Extensions/Date+PeriodOfDates.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryViewController.xib
  BoostPocket/BoostPocket/TravelDetailScene/HistoryHeaderCell.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryHeaderCell.xib
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TotalAmountView.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
Labels: Bug 🐞, Feature 🎨

#180 History 상세화면 직접 수정가능하도록 기능 추가
  BoostPocket/BoostPocket/TravelDetailScene/HistoryDetailViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListViewController.swift
Labels: Feature 🎨

#182 지출/예산 상세, 추가 및 수정화면에서 카테고리 선택기능 구현
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/Extensions/String+IsCategory.swift
  BoostPocket/BoostPocket/Extensions/String+IsPlaceholder.swift
  BoostPocket/BoostPocket/Models/DataModelInfo.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryViewController.xib
  BoostPocket/BoostPocket/TravelDetailScene/CategoryCollectionViewCell.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryDetailViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/MemoEditViewController.swift
Labels: Feature 🎨

#184 전반적인 색상 정리
  BoostPocket/BoostPocket/Assets.xcassets/colors/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/colors/deleteButtonColor.colorset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/colors/deleteTextColor.colorset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/colors/detailExpenseColor.colorset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/colors/detailIncomeColor.colorset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/colors/expenseBackgroundColor.colorset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/colors/expenseTextColor.colorset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/colors/incomeBackgroundColor.colorset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/colors/incomeTextColor.colorset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/colors/lightMainColor.colorset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/colors/mainColor.colorset/Contents.json
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryCell.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryCell.xib
  BoostPocket/BoostPocket/TravelDetailScene/HistoryDetailViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryHeaderCell.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryHeaderCell.xib
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
Labels: Feature 🎨

#189 리포트 화면 파이 그래프 구현
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/TravelDetailScene/ReportPieChartView.swift
  BoostPocket/BoostPocket/TravelDetailScene/ReportPieChartView.xib
  BoostPocket/BoostPocket/TravelDetailScene/ReportViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetailTabbarController.swift
Labels: Feature 🎨

#190 파이그래프, Progress bar 구현, 지출목록 index out of range 버그 수정
  BoostPocket/BoostPocket/Assets.xcassets/colors/category-colors/accommodation-color.colorset/Contents.json
  BoostPocket/BoostPocket/Base.lproj/Main.storyboard
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/ReportPieChartView.swift
  BoostPocket/BoostPocket/TravelDetailScene/ReportViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetailTabbarController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelProfileViewController.swift
  BoostPocket/BoostPocket/TravelListScene/TravelItemViewModel.swift
  BoostPocket/BoostPocket/TravelListScene/View/TravelListViewController.swift
Labels: Bug 🐞, Feature 🎨

#191 프로젝트 폴더에 있는 파일 정리
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/Extensions/Date+/Date+ConvertToString.swift
  BoostPocket/BoostPocket/Extensions/Date+/Date+PeriodOfDates.swift
  BoostPocket/BoostPocket/Extensions/Double+/Double+Comma.swift
  BoostPocket/BoostPocket/Extensions/Double+/Double+NumberFormat.swift
  BoostPocket/BoostPocket/Extensions/String+/String+CurrencySymbol.swift
  BoostPocket/BoostPocket/Extensions/String+/String+IsCategory.swift
  BoostPocket/BoostPocket/Extensions/String+/String+IsPlaceholder.swift
  BoostPocket/BoostPocket/Extensions/String+/String+firstConsonant.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryScene/AddHistoryViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryScene/AddHistoryViewController.xib
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryScene/CategoryCollectionViewCell.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryScene/CategoryCollectionViewCell.xib
  BoostPocket/BoostPocket/TravelDetailScene/HistoryDetailScene/HistoryDetailViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/HistoryFilter.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/HistoryItemViewModel.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/HistoryListSectionHeader.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/HistoryProvider.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/DayCell.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/HistoryCell.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/HistoryCell.xib
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/HistoryHeaderCell.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/HistoryHeaderCell.xib
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/TotalAmountView.swift
  BoostPocket/BoostPocket/TravelDetailScene/ProfileScene/TravelProfileViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/ReportScene/ReportPieChartView.swift
  BoostPocket/BoostPocket/TravelDetailScene/ReportScene/ReportPieChartView.xib
  BoostPocket/BoostPocket/TravelDetailScene/ReportScene/ReportViewController.swift
Labels: Feature 🎨

#193 profile, report 화면 데이터 연결
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/TotalAmountView.swift
  BoostPocket/BoostPocket/TravelDetailScene/ProfileScene/TravelProfileViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/ReportScene/ReportViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
  BoostPocket/BoostPocket/TravelListScene/TravelItemViewModel.swift
Labels: Bug 🐞, Feature 🎨

#194 리포트 화면 구현 완료
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/Assets.xcassets/categories/accommodation-report.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/categories/accommodation-report.imageset/accommodation-report.png
  BoostPocket/BoostPocket/Assets.xcassets/categories/etc-report.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/categories/etc-report.imageset/etc-report.png
  BoostPocket/BoostPocket/Assets.xcassets/categories/food-report.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/categories/food-report.imageset/food-report.png
  BoostPocket/BoostPocket/Assets.xcassets/categories/shopping-report.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/categories/shopping-report.imageset/shopping-report.png
  BoostPocket/BoostPocket/Assets.xcassets/categories/tourism-report.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/categories/tourism-report.imageset/tourism-report.png
  BoostPocket/BoostPocket/Assets.xcassets/categories/transportation-report.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/categories/transportation-report.imageset/transportation-report.png
  BoostPocket/BoostPocket/Assets.xcassets/colors/category-colors/food-color.colorset/Contents.json
  BoostPocket/BoostPocket/Extensions/Double+/Double+getPercentage.swift
  BoostPocket/BoostPocket/Info.plist
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/HistoryCell.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/HistoryCell.xib
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/ProfileScene/TravelProfileViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/ReportScene/ExpenseElementView.swift
  BoostPocket/BoostPocket/TravelDetailScene/ReportScene/ExpenseElementView.xib
  BoostPocket/BoostPocket/TravelDetailScene/ReportScene/ReportPieChartView.swift
  BoostPocket/BoostPocket/TravelDetailScene/ReportScene/ReportViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
  BoostPocket/BoostPocket/TravelListScene/TravelItemViewModel.swift
Labels: Bug 🐞, Feature 🎨

#198 TravelListViewContoller DiffableDataSource에서 reloadData 제거
  BoostPocket/BoostPocket/Constants/Sections.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryScene/AddHistoryViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelListScene/View/TravelCell.swift
  BoostPocket/BoostPocket/TravelListScene/View/TravelHeaderCell.swift
  BoostPocket/BoostPocket/TravelListScene/View/TravelListViewController.swift
Labels: Bug 🐞, Feature 🎨

#204 다크모드 지원
  BoostPocket/BoostPocket/Assets.xcassets/colors/lightMainColor.colorset/Contents.json
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/DayCell.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/TotalAmountView.swift
Labels: Feature 🎨

#206 지출수정화면 스택뷰 간격 조정
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryScene/AddHistoryViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryScene/AddHistoryViewController.xib
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryScene/CategoryCollectionViewCell.xib
Labels: Bug 🐞

#208 지출/예산 수정 및 추가 시 금액이 0원인 경우 예외처리
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryScene/AddHistoryViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryScene/AddHistoryViewController.xib
Labels: Feature 🎨

#211 여행 목록, 지출 목록 divider 구현
  BoostPocket/BoostPocket/Assets.xcassets/newTravel.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/newTravel.imageset/newTravelIndicateImage.png
  BoostPocket/BoostPocket/Base.lproj/Main.storyboard
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
  BoostPocket/BoostPocket/TravelListScene/View/TravelHeaderCell.swift
  BoostPocket/BoostPocket/TravelListScene/View/TravelHeaderCell.xib
  BoostPocket/BoostPocket/TravelListScene/View/TravelListViewController.swift
Labels: Bug 🐞, Feature 🎨

#214 지출 기록이 없는 경우 안내문구가 보이도록 추가
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
Labels: Feature 🎨

#215 제거했던 제약사항 다시 추가
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/TotalAmountView.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
Labels: Bug 🐞

#216 지출이 없을 때 리포트화면 구조 변경
  BoostPocket/BoostPocket/TravelDetailScene/ReportScene/ExpenseElementView.xib
  BoostPocket/BoostPocket/TravelDetailScene/ReportScene/ReportViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
Labels: Feature 🎨

#221 레이블 범위 초과 오류 수정, NaN 에러처리
  BoostPocket/BoostPocket/CustomView/PaddedLabel.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryScene/AddHistoryViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/HistoryCell.xib
  BoostPocket/BoostPocket/TravelDetailScene/ReportScene/ReportPieChartView.swift
  BoostPocket/BoostPocket/TravelDetailScene/ReportScene/ReportViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
  BoostPocket/BoostPocket/TravelListScene/TravelItemViewModel.swift
  BoostPocket/BoostPocket/TravelListScene/View/TravelCell.xib
  BoostPocket/BoostPocket/TravelListScene/View/TravelHeaderCell.xib
Labels: Bug 🐞

#220 프로필 화면 예산 관련 디자인 수정
  BoostPocket/BoostPocket/TravelDetailScene/ProfileScene/TravelProfileViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
Labels: Feature 🎨

#222 TravelItemViewModel 추가 테스트 작성
  BoostPocket/BoostPocketTests/TravelTests/TravelViewModelTests.swift
Labels: Test :test_tube:

#223 NaN/Infinite number 에러핸들링
  BoostPocket/BoostPocket/TravelDetailScene/ProfileScene/TravelProfileViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/ReportScene/ReportViewController.swift
  BoostPocket/BoostPocket/TravelListScene/TravelItemViewModel.swift
  BoostPocket/BoostPocket/TravelListScene/View/TravelCell.xib
  BoostPocket/BoostPocketTests/TravelTests/TravelViewModelTests.swift
Labels: Bug 🐞

#224 Date 관련 이슈 수정
  BoostPocket/BoostPocket/Extensions/Date+/Date+ConvertToString.swift
  BoostPocket/BoostPocket/Extensions/Date+/Date+PeriodOfDates.swift
  BoostPocket/BoostPocket/Models/PersistenceManager.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/HistoryListViewController.swift
  BoostPocket/BoostPocketTests/CountryTests/CountryProviderTests.swift
  BoostPocket/BoostPocketTests/CountryTests/CountryViewModelTests.swift
  BoostPocket/BoostPocketTests/HistoryTests/HistoryProviderTests.swift
  BoostPocket/BoostPocketTests/HistoryTests/HistoryViewModelTests.swift
  BoostPocket/BoostPocketTests/PersistenceManagerTests/PersistenceManagerTests.swift
  BoostPocket/BoostPocketTests/TravelTests/TravelViewModelTests.swift
Labels: Bug 🐞

#227 piechart 버그 수정
  BoostPocket/BoostPocket/Extensions/Date+/Date+PeriodOfDates.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryScene/AddHistoryViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/ReportScene/ReportPieChartView.swift
  BoostPocket/BoostPocket/TravelDetailScene/ReportScene/ReportViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
Labels: HotFix 🚨

#228 지출수정화면 스택뷰 간격조정, 지출목록화면 선택한 날짜 정보 viewWillAppear에서 반영
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/Extensions/Date+/Date+PeriodOfDates.swift
  BoostPocket/BoostPocket/Extensions/Date+/Date+isValidInRange.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryScene/AddHistoryViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryScene/AddHistoryViewController.xib
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/DayCell.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetailTabbarController.swift
Labels: HotFix 🚨

#233 코어데이터 Update 비동기로 함수구조 변경
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket.xcodeproj/xcshareddata/xcschemes/BoostPocket.xcscheme
  BoostPocket/BoostPocket/Base.lproj/Main.storyboard
  BoostPocket/BoostPocket/Models/PersistenceManager.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/HistoryProvider.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelListScene/TravelItemViewModel.swift
  BoostPocket/BoostPocket/TravelListScene/TravelListViewModel.swift
  BoostPocket/BoostPocket/TravelListScene/TravelProvider.swift
  BoostPocket/BoostPocket/TravelListScene/View/TravelListViewController.swift
  BoostPocket/BoostPocketTests/HistoryTests/HistoryProviderTests.swift
  BoostPocket/BoostPocketTests/HistoryTests/HistoryViewModelTests.swift
  BoostPocket/BoostPocketTests/PersistenceManagerTests/PersistenceManagerTests.swift
  BoostPocket/BoostPocketTests/TravelListVCTests.swift
  BoostPocket/BoostPocketTests/TravelTests/TravelProviderTests.swift
  BoostPocket/BoostPocketTests/TravelTests/TravelViewModelTests.swift
Labels: Test :test_tube:

#234 HistoryListVC FloatingButton Tapping 테스트
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
  BoostPocket/BoostPocketTests/HistoryListVCTests.swift
  BoostPocket/BoostPocketTests/TravelTests/TravelProviderTests.swift
Labels: Test :test_tube:

#236 TravelProfile 테스트 및 구조 변경
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/Models/PersistenceManager.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/HistoryListSupport.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/ProfileScene/TravelProfileViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
  BoostPocket/BoostPocket/TravelListScene/TravelListSupport.swift
  BoostPocket/BoostPocket/TravelListScene/TravelListViewModel.swift
  BoostPocket/BoostPocket/TravelListScene/TravelProvider.swift
  BoostPocket/BoostPocket/TravelListScene/View/TravelListViewController.swift
  BoostPocket/BoostPocketTests/TravelListVCTests.swift
  BoostPocket/BoostPocketTests/TravelProfileVCTests.swift
Labels: Bug 🐞, Refactoring ✒, Test :test_tube:

#240 TotalAmountView 설정 이슈 수정
  BoostPocket/BoostPocket/Base.lproj/Main.storyboard
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/TotalAmountView.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
Labels: Bug 🐞

#241 지출 추가화면에서 숫자가 커질 때 발생하는 문제 해결
  BoostPocket/BoostPocket/Extensions/Double+/Double+NumberFormat.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryScene/AddHistoryViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryScene/AddHistoryViewController.xib
  BoostPocket/BoostPocket/TravelDetailScene/HistoryDetailScene/HistoryDetailViewController.swift
Labels: Bug 🐞

#243 floating button 코드 수정 및 지출 레이블 제약사항 변경
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/HistoryCell.xib
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/HistoryListViewController.swift
Labels: Bug 🐞

#246 지출/예산 추가화면 DatePicker 깨지는 문제 해결
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryScene/AddHistoryViewController.xib
Labels: Bug 🐞

#251 여행목록 TravelCell Title/금액 constraint 변경
  BoostPocket/BoostPocket/TravelListScene/View/TravelCell.xib
Labels: Bug 🐞

#253 여행 프로필 화면에서 타이틀 수정 시 navbar 반영
  BoostPocket/BoostPocket/TravelDetailScene/ProfileScene/TravelProfileViewController.swift
Labels: Bug 🐞

#256 PersistenceManager - createCountries 함수 수정
  BoostPocket/BoostPocket/Models/PersistenceManager.swift
  BoostPocket/BoostPocket/SceneDelegate.swift
  BoostPocket/NetworkManager/DataLoader.swift
Labels: Bug 🐞

#258 여행리스트 정렬 적용
  BoostPocket/BoostPocket/TravelListScene/TravelListViewModel.swift
  BoostPocket/BoostPocket/TravelListScene/View/TravelListViewController.swift
Labels: Feature 🎨

#259 PersistenceManager 테스트코드 보강
  BoostPocket/BoostPocket/Models/PersistenceManager.swift
  BoostPocket/BoostPocketTests/PersistenceManagerTests/PersistenceManagerTests.swift
Labels: Test :test_tube:

#261 사용하지 않는 메소드 삭제
  BoostPocket/BoostPocket/CountryListScene/CountryListViewModel.swift
  BoostPocket/BoostPocket/TravelListScene/TravelItemViewModel.swift
  BoostPocket/BoostPocket/TravelListScene/TravelListViewModel.swift
Labels: Bug 🐞

#262 PieChartView 주석 삭제
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/TotalAmountView.swift
  BoostPocket/BoostPocket/TravelDetailScene/ReportScene/ReportPieChartView.swift
  BoostPocket/BoostPocket/TravelDetailScene/ReportScene/ReportViewController.swift
Labels: Refactoring ✒

#263 FloatingButton DispatchQueue에서 돌아가도록 수정
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/HistoryListSupport.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/HistoryListViewController.swift
  BoostPocket/BoostPocketTests/HistoryListVCTests.swift
Labels: Bug 🐞

#267 마스터 클래스 피드백 반영
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryScene/AddHistoryViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/MemoEditViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/ProfileScene/TravelProfileViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TitleEditViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
Labels: Bug 🐞

#269 예산 추가/수정 시 화면에 정보 보여주는 뷰 추가
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryScene/AddHistoryViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryScene/AddHistoryViewController.xib
Labels: Feature 🎨

#271 지출/예산 추가화면의 Alert 메시지 수정
  BoostPocket/BoostPocket/Base.lproj/Main.storyboard
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryScene/AddHistoryViewController.swift
Labels: Bug 🐞

#272 DisplayName 한글 지원
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/en.lproj/InfoPlist.strings
  BoostPocket/BoostPocket/ko.lproj/InfoPlist.strings
  BoostPocket/BoostPocket/ko.lproj/LaunchScreen.strings
  BoostPocket/BoostPocket/ko.lproj/Main.strings
Labels: Feature 🎨

#273 다크모드 미적용 된 부분 수정
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryScene/AddHistoryViewController.swift
Labels: Bug 🐞

#274 화면 상단 제목 한글로 변경
  BoostPocket/BoostPocket/Base.lproj/Main.storyboard
  BoostPocket/BoostPocket/ko.lproj/Main.strings
Labels: Refactoring ✒

#277 DatePicker 색상 변경
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryScene/AddHistoryViewController.xib
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/HistoryCell.xib
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
Labels: Feature 🎨

#278 여행 삭제 성공 시 햅틱반응 구현
  BoostPocket/BoostPocket/TravelListScene/View/TravelListViewController.swift
Labels: Feature 🎨

#280 국가 선택 화면 테이블뷰 selection 버그 수정
  BoostPocket/BoostPocket/CountryListScene/View/CountryListViewController.swift
Labels: Bug 🐞

#283 savebutton 색상, datePicker color set 생성
  BoostPocket/BoostPocket/Assets.xcassets/colors/basicDarkGrayTextColor.colorset/Contents.json
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryScene/AddHistoryViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryScene/AddHistoryViewController.xib
Labels: Feature 🎨

#284 stackView leading, trailing constraint 조정
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryScene/AddHistoryViewController.xib
Labels: Refactoring ✒

#286 FloatingButton Open/Close에 대한 테스트코드 작성
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/HistoryListViewController.swift
  BoostPocket/BoostPocketTests/HistoryListVCTests.swift
  BoostPocket/BoostPocketTests/TravelListVCTests.swift
Labels: Test :test_tube:

#285 다크모드에 대응하기위한 일부 색상 수정
  BoostPocket/BoostPocket/Assets.xcassets/colors/basicDarkGrayTextColor.colorset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/isPrepareTrue.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/isPrepareTrue.imageset/isPrepareTrue-dark.png
  BoostPocket/BoostPocket/Base.lproj/Main.storyboard
  BoostPocket/BoostPocket/CountryListScene/View/CountryListViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/AddHistoryScene/AddHistoryViewController.xib
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
Labels: Bug 🐞

#287 잔버그 수정
  BoostPocket/BoostPocket/CountryListScene/View/CountryListViewController.swift
  BoostPocket/BoostPocket/TravelListScene/View/TravelListViewController.swift
Labels: Bug 🐞

#289 프로젝트 내에 있는 print문 주석처리
  BoostPocket/BoostPocket/Models/PersistenceManager.swift
  BoostPocket/BoostPocket/SceneDelegate.swift
  BoostPocket/BoostPocket/TravelDetailScene/HistoryListScene/View/HistoryListViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/ProfileScene/TravelProfileViewController.swift
  BoostPocket/BoostPocket/TravelListScene/View/TravelListViewController.swift
  BoostPocket/NetworkManager/DataLoader.swift
Labels: HotFix 🚨

#290 App Store 배포를 위한 appIcon 알파값제거
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/Assets.xcassets/AppIcon.appiconset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/AppIcon.appiconset/Icon-1024.png
  BoostPocket/BoostPocket/Assets.xcassets/AppIcon.appiconset/Icon-120.png
  BoostPocket/BoostPocket/Assets.xcassets/AppIcon.appiconset/Icon-152.png
  BoostPocket/BoostPocket/Assets.xcassets/AppIcon.appiconset/Icon-167.png
  BoostPocket/BoostPocket/Assets.xcassets/AppIcon.appiconset/Icon-180.png
  BoostPocket/BoostPocket/Assets.xcassets/AppIcon.appiconset/Icon-76.png
  BoostPocket/BoostPocket/Assets.xcassets/AppIcon.appiconset/appIcon.png
  BoostPocket/BoostPocket/Assets.xcassets/AppIcon.appiconset/appIcon1024.png
  BoostPocket/BoostPocket/Assets.xcassets/AppIcon.appiconset/appIcon120.png
  BoostPocket/BoostPocket/Assets.xcassets/AppIcon.appiconset/appIcon152.png
  BoostPocket/BoostPocket/Assets.xcassets/AppIcon.appiconset/appIcon167.png
  BoostPocket/BoostPocket/Assets.xcassets/AppIcon.appiconset/appIcon76.png
Labels: HotFix 🚨

#296 국가 목록 화면 네트워크 요청 메세지 버그 수정
  BoostPocket/BoostPocket/CountryListScene/View/CountryListViewController.swift
Labels: Bug 🐞

#297 v1.0.1 배포
  BoostPocket/BoostPocket/CountryListScene/View/CountryListViewController.swift
Labels: Release 🔖

#298 v1.0.1 배포
  BoostPocket/BoostPocket/CountryListScene/View/CountryListViewController.swift
Labels: Release 🔖

#299 Version update 1.0 -> 1.0.1
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/Info.plist
Labels: HotFix 🚨
