Repository boostcamp-2020/Project18-A-BoostPocket, pull requests merged in 2020-11, with the labels that each got.

#7 프로젝트 생성
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  BoostPocket/BoostPocket.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  BoostPocket/BoostPocket/AppDelegate.swift
  BoostPocket/BoostPocket/Assets.xcassets/AppIcon.appiconset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/Contents.json
  BoostPocket/BoostPocket/Base.lproj/LaunchScreen.storyboard
  BoostPocket/BoostPocket/Base.lproj/Main.storyboard
  BoostPocket/BoostPocket/BoostPocket.xcdatamodeld/.xccurrentversion
  BoostPocket/BoostPocket/BoostPocket.xcdatamodeld/BoostPocket.xcdatamodel/contents
  BoostPocket/BoostPocket/Info.plist
  BoostPocket/BoostPocket/SceneDelegate.swift
  BoostPocket/BoostPocket/ViewController.swift
  BoostPocket/BoostPocketTests/BoostPocketTests.swift
  BoostPocket/BoostPocketTests/Info.plist
Labels: Configure ⚙, Feature 🎨

#12 release <- dev
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  BoostPocket/BoostPocket.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  BoostPocket/BoostPocket/AppDelegate.swift
  BoostPocket/BoostPocket/Assets.xcassets/AppIcon.appiconset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/Contents.json
  BoostPocket/BoostPocket/Base.lproj/LaunchScreen.storyboard
  BoostPocket/BoostPocket/Base.lproj/Main.storyboard
  BoostPocket/BoostPocket/BoostPocket.xcdatamodeld/.xccurrentversion
  BoostPocket/BoostPocket/BoostPocket.xcdatamodeld/BoostPocket.xcdatamodel/contents
  BoostPocket/BoostPocket/CountryCell.swift
  BoostPocket/BoostPocket/CountryCell.xib
  BoostPocket/BoostPocket/CountryListViewController.swift
  BoostPocket/BoostPocket/CountryListViewController.xib
  BoostPocket/BoostPocket/Info.plist
  BoostPocket/BoostPocket/SceneDelegate.swift
  BoostPocket/BoostPocket/TravelDetail.storyboard
  BoostPocket/BoostPocket/TravelListViewController.swift
  BoostPocket/BoostPocket/TravelProfileViewController.swift
  BoostPocket/BoostPocket/ViewController.swift
  BoostPocket/BoostPocketTests/BoostPocketTests.swift
  BoostPocket/BoostPocketTests/Info.plist
Labels: Release

#13 master <- release
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  BoostPocket/BoostPocket.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  BoostPocket/BoostPocket/AppDelegate.swift
  BoostPocket/BoostPocket/Assets.xcassets/AppIcon.appiconset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/Contents.json
  BoostPocket/BoostPocket/Base.lproj/LaunchScreen.storyboard
  BoostPocket/BoostPocket/Base.lproj/Main.storyboard
  BoostPocket/BoostPocket/BoostPocket.xcdatamodeld/.xccurrentversion
  BoostPocket/BoostPocket/BoostPocket.xcdatamodeld/BoostPocket.xcdatamodel/contents
  BoostPocket/BoostPocket/CountryCell.swift
  BoostPocket/BoostPocket/CountryCell.xib
  BoostPocket/BoostPocket/CountryListViewController.swift
  BoostPocket/BoostPocket/CountryListViewController.xib
  BoostPocket/BoostPocket/Info.plist
  BoostPocket/BoostPocket/SceneDelegate.swift
  BoostPocket/BoostPocket/TravelDetail.storyboard
  BoostPocket/BoostPocket/TravelListViewController.swift
  BoostPocket/BoostPocket/TravelProfileViewController.swift
  BoostPocket/BoostPocket/ViewController.swift
  BoostPocket/BoostPocketTests/BoostPocketTests.swift
  BoostPocket/BoostPocketTests/Info.plist
Labels: Demo 📱

#18 Podfile 추가, 환율 API 요청을 위한 네트워크 모델 구현
  BoostPocket/.swiftlint.yml
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket.xcworkspace/contents.xcworkspacedata
  BoostPocket/BoostPocket.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  BoostPocket/BoostPocket/AppDelegate.swift
  BoostPocket/BoostPocket/SceneDelegate.swift
  BoostPocket/BoostPocket/TravelListViewController.swift
  BoostPocket/BoostPocket/TravelProfileViewController.swift
  BoostPocket/BoostPocket/ViewController.swift
  BoostPocket/NetworkManager/DataLoader.swift
  BoostPocket/NetworkManager/Info.plist
  BoostPocket/NetworkManager/NetworkManager.h
  BoostPocket/NetworkManagerTests/Info.plist
  BoostPocket/NetworkManagerTests/NetworkManagerTests.swift
  BoostPocket/Podfile
  BoostPocket/Podfile.lock
Labels: Feature 🎨, Test :test_tube:

#21 코어데이터 엔티티 생성, CountryProvider 및 테스트코드 작성
  BoostPocket/.swiftlint.yml
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/AppDelegate.swift
  BoostPocket/BoostPocket/BoostPocket.xcdatamodeld/BoostPocket.xcdatamodel/contents
  BoostPocket/BoostPocket/CoreDataModels/Country+CoreDataClass.swift
  BoostPocket/BoostPocket/CoreDataModels/Country+CoreDataProperties.swift
  BoostPocket/BoostPocket/CoreDataModels/Travel+CoreDataClass.swift
  BoostPocket/BoostPocket/CoreDataModels/Travel+CoreDataProperties.swift
  BoostPocket/BoostPocket/CountryListScene/CountryCell.swift
  BoostPocket/BoostPocket/CountryListScene/CountryCell.xib
  BoostPocket/BoostPocket/CountryListScene/CountryListViewController.swift
  BoostPocket/BoostPocket/CountryListScene/CountryListViewController.xib
  BoostPocket/BoostPocket/CountryListScene/CountryProvider.swift
  BoostPocket/BoostPocket/PersistenceManager.swift
  BoostPocket/BoostPocket/SceneDelegate.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
  BoostPocket/BoostPocket/TravelDetailScene/TravelProfileViewController.swift
  BoostPocket/BoostPocket/TravelListScene/TravelListViewController.swift
  BoostPocket/BoostPocketTests/CountryProviderStub.swift
  BoostPocket/BoostPocketTests/CountryProviderTests.swift
  BoostPocket/BoostPocketTests/PersistenceManagerStub.swift
  BoostPocket/BoostPocketTests/PersistenceManagerTests.swift
  BoostPocket/NetworkManagerTests/NetworkManagerTests.swift
Labels: Feature 🎨, Test :test_tube:

#22 국가 정보 저장 구현
  BoostPocket/BoostPocket/SceneDelegate.swift
  BoostPocket/NetworkManager/DataLoader.swift
Labels: Feature 🎨

#24 Country 뷰모델 구현
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/Base.lproj/Main.storyboard
  BoostPocket/BoostPocket/BoostPocket.xcdatamodeld/BoostPocket.xcdatamodel/contents
  BoostPocket/BoostPocket/CoreDataModels/Country+CoreDataClass.swift
  BoostPocket/BoostPocket/CountryListScene/CountryCell.swift
  BoostPocket/BoostPocket/CountryListScene/CountryCell.xib
  BoostPocket/BoostPocket/CountryListScene/CountryItemViewModel.swift
  BoostPocket/BoostPocket/CountryListScene/CountryListViewController.swift
  BoostPocket/BoostPocket/CountryListScene/CountryListViewModel.swift
  BoostPocket/BoostPocket/CountryListScene/CountryProvider.swift
  BoostPocket/BoostPocket/SceneDelegate.swift
  BoostPocket/BoostPocket/TravelListScene/TravelListViewController.swift
  BoostPocket/BoostPocketTests/CountryProviderStub.swift
  BoostPocket/BoostPocketTests/CountryProviderTests.swift
  BoostPocket/BoostPocketTests/CountryViewModelTests.swift
  BoostPocket/BoostPocketTests/PersistenceManagerStub.swift
  BoostPocket/Podfile
  BoostPocket/Podfile.lock
Labels: Bug 🐞, Feature 🎨

#26 SceneDelegate 리팩토링
  BoostPocket/.swiftlint.yml
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/CountryListScene/CountryCell.swift
  BoostPocket/BoostPocket/CountryListScene/CountryListViewController.swift
  BoostPocket/BoostPocket/CountryListScene/CountryListViewModel.swift
  BoostPocket/BoostPocket/CountryListScene/CountryProvider.swift
  BoostPocket/BoostPocket/PersistenceManager.swift
  BoostPocket/BoostPocket/SceneDelegate.swift
Labels: Feature 🎨, Refactoring ✒

#27 CountryListViewController 구조 개선
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/CountryListScene/CountryItemViewModel.swift
  BoostPocket/BoostPocket/CountryListScene/CountryListViewController.swift
  BoostPocket/BoostPocket/CountryListScene/CountryListViewModel.swift
  BoostPocket/BoostPocket/SceneDelegate.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
  BoostPocket/BoostPocket/TravelListScene/TravelListViewController.swift
  BoostPocket/BoostPocket/TravelListScene/TravleListViewModel.swift
Labels: Refactoring ✒

#32 CountryViewModel / CountryProvider 테스트코드 작성 완료
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/CountryListScene/CountryListViewModel.swift
  BoostPocket/BoostPocket/CountryListScene/CountryProvider.swift
  BoostPocket/BoostPocket/PersistenceManager.swift
  BoostPocket/BoostPocketTests/BoostPocketTests.swift
  BoostPocket/BoostPocketTests/CountryProviderStub.swift
  BoostPocket/BoostPocketTests/CountryProviderTests.swift
  BoostPocket/BoostPocketTests/CountryTests/CountryProviderTests.swift
  BoostPocket/BoostPocketTests/CountryTests/CountryStub.swift
  BoostPocket/BoostPocketTests/CountryTests/CountryViewModelTests.swift
  BoostPocket/BoostPocketTests/CountryViewModelTests.swift
Labels: Refactoring ✒, Test :test_tube:

#31 CountryList화면에 SectionIndexTitle 적용 완료
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/CountryListScene/CountryListViewController.swift
  BoostPocket/BoostPocket/Extension/String+Extension.swift
Labels: Feature 🎨

#37 국가 선택 시, 올바른 국가 정보 반환
  BoostPocket/BoostPocket/CountryListScene/CountryListViewController.swift
  BoostPocket/BoostPocket/Extension/String+Extension.swift
Labels: Bug 🐞

#40 PersistenceManage createCountry 함수 구현
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/CountryListScene/CountryInfo.swift
  BoostPocket/BoostPocket/CountryListScene/CountryProvider.swift
  BoostPocket/BoostPocket/PersistenceManager.swift
  BoostPocket/BoostPocketTests/PersistenceManagerTests/PersistenceManagerStub.swift
  BoostPocket/BoostPocketTests/PersistenceManagerTests/PersistenceManagerTests.swift
Labels: Refactoring ✒, Test :test_tube:

#42 PersistenceManager createObject 함수 개선
  BoostPocket/BoostPocket/CoreDataModels/Country+CoreDataClass.swift
  BoostPocket/BoostPocket/CountryListScene/CountryInfo.swift
  BoostPocket/BoostPocket/CountryListScene/CountryProvider.swift
  BoostPocket/BoostPocket/PersistenceManager.swift
  BoostPocket/BoostPocket/TravelListScene/TravelProvider.swift
  BoostPocket/BoostPocketTests/PersistenceManagerTests/PersistenceManagerTests.swift
  BoostPocket/Travel+CoreDataClass.swift
  BoostPocket/TravelProviderTests.swift
Labels: Refactoring ✒

#43 PersistenceManager delete 함수 구현
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/CountryListScene/countryType.swift
  BoostPocket/BoostPocket/PersistenceManager.swift
  BoostPocket/BoostPocketTests/PersistenceManagerTests/PersistenceManagerTests.swift
Labels: Feature 🎨, Test :test_tube:

#46 함수명, 코드 정리
  BoostPocket/.swiftlint.yml
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/CountryListScene/CountryListViewController.swift
  BoostPocket/BoostPocket/DataModelInfo.swift
  BoostPocket/BoostPocket/History+CoreDataProperties.swift
  BoostPocket/BoostPocket/PersistenceManager.swift
  BoostPocket/BoostPocket/TravelListScene/TravelItemViewModel.swift
  BoostPocket/BoostPocket/TravelListScene/TravelListViewModel.swift
  BoostPocket/BoostPocket/TravelListScene/TravelProvider.swift
  BoostPocket/BoostPocketTests/PersistenceManagerTests/PersistenceManagerTests.swift
  BoostPocket/NetworkManager/DataLoader.swift
  BoostPocket/NetworkManagerTests/NetworkManagerTests.swift
  BoostPocket/Travel+CoreDataProperties.swift
  BoostPocket/TravelProviderTests.swift
Labels: Refactoring ✒

#48 TravelListViewModel create 메소드 구현
  BoostPocket/BoostPocket/TravelListScene/TravelItemViewModel.swift
  BoostPocket/BoostPocket/TravelListScene/TravelListViewModel.swift
  BoostPocket/BoostPocket/TravelListScene/TravelViewModelTests.swift
Labels: Feature 🎨, Test :test_tube:

#49 Country/Travel Provider에서 discardableResult 제거
  BoostPocket/BoostPocket/CountryListScene/CountryProvider.swift
  BoostPocket/BoostPocket/TravelListScene/TravelProvider.swift
  BoostPocket/BoostPocket/TravelListScene/TravelViewModelTests.swift
  BoostPocket/BoostPocketTests/CountryTests/CountryProviderTests.swift
  BoostPocket/BoostPocketTests/CountryTests/CountryViewModelTests.swift
  BoostPocket/TravelProviderTests.swift
Labels: Refactoring ✒

#51 TravelListViewModel 메소드 구현
  BoostPocket/BoostPocket/CountryListScene/CountryListViewModel.swift
  BoostPocket/BoostPocket/PersistenceManager.swift
  BoostPocket/BoostPocket/TravelListScene/TravelListViewModel.swift
  BoostPocket/BoostPocket/TravelListScene/TravelViewModelTests.swift
Labels: Feature 🎨, Refactoring ✒, Test :test_tube:

#56 레이아웃 마지막 TravelCell 구현
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/TravelListScene/LongTravelCell.swift
  BoostPocket/BoostPocket/TravelListScene/LongTravelCell.xib
Labels: Feature 🎨

#58 여행 목록 화면 CollectionView Header 적용 및 cell 레이아웃 구현
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/Assets.xcassets/default.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/default.imageset/default.png
  BoostPocket/BoostPocket/Assets.xcassets/hamburger.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/hamburger.imageset/hamburger.png
  BoostPocket/BoostPocket/Assets.xcassets/rectangle.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/rectangle.imageset/rectangle.png
  BoostPocket/BoostPocket/Assets.xcassets/square.imageset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/square.imageset/smallsquares.png
  BoostPocket/BoostPocket/Base.lproj/Main.storyboard
  BoostPocket/BoostPocket/TravelListScene/TravelHeaderCell.swift
  BoostPocket/BoostPocket/TravelListScene/TravelHeaderCell.xib
  BoostPocket/BoostPocket/TravelListScene/TravelListHeader.swift
  BoostPocket/BoostPocket/TravelListScene/TravelListViewController.swift
Labels: Feature 🎨

#57 TravelListViewModel delete 함수 구현 및 테스트코드 작성
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/Assets.xcassets/DeleteButtonColor.colorset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/mainColor.colorset/Contents.json
  BoostPocket/BoostPocket/Base.lproj/Main.storyboard
  BoostPocket/BoostPocket/Extension/Data+ImageData.swift
  BoostPocket/BoostPocket/Extension/String+firstConsonant.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetailTabbarController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelProfileViewController.swift
  BoostPocket/BoostPocket/TravelListScene/TravelCell.xib
  BoostPocket/BoostPocket/TravelListScene/TravelListViewController.swift
  BoostPocket/BoostPocket/TravelListScene/TravelListViewModel.swift
  BoostPocket/BoostPocket/TravelListScene/TravelProvider.swift
  BoostPocket/BoostPocketTests/TravelTests/TravelViewModelTests.swift
Labels: Feature 🎨

#59 여행 생성 버튼 안보이는 버그, 헤더 여행 개수 버그 수정
  BoostPocket/BoostPocket/Base.lproj/Main.storyboard
  BoostPocket/BoostPocket/TravelListScene/TravelHeaderCell.swift
  BoostPocket/BoostPocket/TravelListScene/TravelHeaderCell.xib
  BoostPocket/BoostPocket/TravelListScene/TravelListViewController.swift
Labels: Bug 🐞

#61 프로젝트 디렉토리 정리
  BoostPocket/BoostPocket/Constants/Sections.swift
  BoostPocket/BoostPocket/CountryListScene/View/CountryCell.swift
  BoostPocket/BoostPocket/CountryListScene/View/CountryCell.xib
  BoostPocket/BoostPocket/CountryListScene/View/CountryListViewController.swift
  BoostPocket/BoostPocket/CountryListScene/View/CountryListViewController.xib
  BoostPocket/BoostPocket/Extensions/Data+ImageData.swift
  BoostPocket/BoostPocket/Extensions/Date+ConvertToString.swift
  BoostPocket/BoostPocket/Extensions/String+firstConsonant.swift
  BoostPocket/BoostPocket/Models/DataModelInfo.swift
  BoostPocket/BoostPocket/Models/PersistenceManager.swift
  BoostPocket/BoostPocket/TravelDetailScene/View/TravelDetail.storyboard
  BoostPocket/BoostPocket/TravelDetailScene/View/TravelDetailTabbarController.swift
  BoostPocket/BoostPocket/TravelDetailScene/View/TravelProfileViewController.swift
  BoostPocket/BoostPocket/TravelListScene/View/LongTravelCell.swift
  BoostPocket/BoostPocket/TravelListScene/View/LongTravelCell.xib
  BoostPocket/BoostPocket/TravelListScene/View/TravelCell.swift
  BoostPocket/BoostPocket/TravelListScene/View/TravelCell.xib
  BoostPocket/BoostPocket/TravelListScene/View/TravelHeaderCell.swift
  BoostPocket/BoostPocket/TravelListScene/View/TravelHeaderCell.xib
  BoostPocket/BoostPocket/TravelListScene/View/TravelListViewController.swift
Labels: HotFix 🚨, Release 🔖

#64 TravelDetailScene filepath 수정
  BoostPocket/BoostPocket/Assets.xcassets/AppIcon.appiconset/Contents.json
  BoostPocket/BoostPocket/Assets.xcassets/AppIcon.appiconset/image.png
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetailTabbarController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelProfileViewController.swift
Labels: HotFix 🚨, Release 🔖

#81 CoreData에서 Travel Update 기능 구현
  .github/workflows/UnitTests.yml
  BoostPocket/BoostPocket.xcodeproj/xcshareddata/xcschemes/BoostPocket.xcscheme
  BoostPocket/BoostPocket.xcodeproj/xcshareddata/xcschemes/BoostPocketTests.xcscheme
  BoostPocket/BoostPocket.xcodeproj/xcshareddata/xcschemes/NetworkManager.xcscheme
  BoostPocket/BoostPocket.xcodeproj/xcshareddata/xcschemes/NetworkManagerTests.xcscheme
  BoostPocket/BoostPocket/CountryListScene/CountryProvider.swift
  BoostPocket/BoostPocket/Models/DataModelInfo.swift
  BoostPocket/BoostPocket/Models/PersistenceManager.swift
  BoostPocket/BoostPocket/TravelListScene/TravelProvider.swift
  BoostPocket/BoostPocketTests/PersistenceManagerTests/PersistenceManagerTests.swift
Labels: Feature 🎨, Test :test_tube:

#84 여행 프로필 화면 구현
  BoostPocket/BoostPocket/Assets.xcassets/deleteTextColor.colorset/Contents.json
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
Labels: Feature 🎨

#86 여행 업데이트 기능 추가
  BoostPocket/BoostPocket/CountryListScene/CountryProvider.swift
  BoostPocket/BoostPocket/TravelListScene/TravelItemViewModel.swift
  BoostPocket/BoostPocket/TravelListScene/TravelListViewModel.swift
  BoostPocket/BoostPocket/TravelListScene/TravelProvider.swift
  BoostPocket/BoostPocketTests/TravelTests/TravelProviderTests.swift
  BoostPocket/BoostPocketTests/TravelTests/TravelViewModelTests.swift
Labels: Feature 🎨, Test :test_tube:

#87 여행 프로필 메모 화면 UI 구현
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/TravelDetailScene/MemoEditViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
  BoostPocket/BoostPocket/TravelDetailScene/TravelProfileViewController.swift
Labels: Feature 🎨

#90 Memo 수정 기능 구현
  BoostPocket/BoostPocket.xcodeproj/project.pbxproj
  BoostPocket/BoostPocket/TravelDetailScene/MemoEditViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
  BoostPocket/BoostPocket/TravelDetailScene/TravelProfileViewController.swift
  BoostPocket/BoostPocket/TravelListScene/View/LongTravelCell.swift
  BoostPocket/BoostPocket/TravelListScene/View/LongTravelCell.xib
  BoostPocket/BoostPocket/TravelListScene/View/TravelListViewController.swift
Labels: Feature 🎨

#92 여행 타이틀, 메모 수정 시 키보드가 뷰를 가리지 않도록 구현
  BoostPocket/BoostPocket/TravelDetailScene/MemoEditViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TitleEditViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
  BoostPocket/BoostPocket/TravelDetailScene/TravelProfileViewController.swift
Labels: Feature 🎨

#93 TravelProfile - title, memo 업데이트 기능 구현
  BoostPocket/BoostPocket/TravelDetailScene/MemoEditViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TitleEditViewController.swift
  BoostPocket/BoostPocket/TravelDetailScene/TravelDetail.storyboard
  BoostPocket/BoostPocket/TravelDetailScene/TravelProfileViewController.swift
Labels: Feature 🎨
